### ISSUE TITLE
Table row borders are not displayed when applied to <tr>

### ISSUE THREAD

**Issue by siegelzc** [openhtmltopdf/openhtmltopdf#34]
#### This does not work:
```css
table {
  border-collapse: collapse;
}
table > tbody > tr {
  border-bottom: 1px solid rgb(245, 245, 245);
}
```
<img width="486" alt="Screenshot 2024-04-24 at 1 26 34 PM" src="https://github.com/openhtmltopdf/openhtmltopdf/assets/15002786/63bfd1ac-bdc5-45d3-b46d-9a4bee03f95c">

#### Must do this:
```css
table {
  border-collapse: collapse;
}
table > tbody > tr > td {
  border-bottom: 1px solid rgb(245, 245, 245);
}
```
<img width="482" alt="Screenshot 2024-04-24 at 1 26 18 PM" src="https://github.com/openhtmltopdf/openhtmltopdf/assets/15002786/89205f98-6995-432a-b19c-2443f002c81e">
